# Generated by Django 3.1.2 on 2020-10-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total', models.IntegerField()),
                ('users', models.JSONField()),
                ('last_update', models.DateTimeField(verbose_name='date updated')),
            ],
            options={
                'db_table': 'host_users',
            },
        ),
        migrations.CreateModel(
            name='User_Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total', models.IntegerField()),
                ('hosts', models.JSONField()),
                ('last_update', models.DateTimeField(verbose_name='date updated')),
            ],
            options={
                'db_table': 'user_hosts',
            },
        ),
    ]
