version: '3.7'

services:
  saltui:
    build:
      context: .
    image: saltui
    container_name: saltui
    # DB USER and PASSWORD set in data_files/db-init-scripts/init-user-db.sh
    env_file: .env.saltui
    # environment:
    #   SALTUI_ALLOWED_HOSTS: ${SALTUI_ALLOWED_HOSTS}
    #   SALTUI_APP_BASE_DOMAIN: ${SALTUI_APP_BASE_DOMAIN}
    #   SALTUI_DB_HOST: ${SALTUI_DB_HOST}
    #   SALTUI_DB_PASS: ${SALTUI_DB_PASS}
    #   SALTUI_DB_USER: ${SALTUI_DB_USER}
    #   SALTUI_SALT_API_HOST: ${SALTUI_SALT_API_HOST}
    #   SALTUI_SALT_API_EAUTH: ${SALTUI_SALT_API_EAUTH}
    #   SALTUI_SALT_API_PASS: ${SALTUI_SALT_API_PASS}
    #   SALTUI_SALT_API_USER: ${SALTUI_SALT_API_USER}
    volumes:
      - $PWD:/opt/saltui
    ports:
      - 8000:8000
      - 8443:8443
    command: ['wait-for', 'postgres:5432', '-t', '30', '--', 'python', 'manage.py', 'runserver', '0.0.0.0:8000']
    restart: unless-stopped
    depends_on:
      - postgres
      - keycloak
  
  postgres:
    image: postgres:13-alpine
    env_file: .env.postgres
    # environment:
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_APP_USER: ${POSTGRES_APP_USER}
    #   POSTGRES_APP_PASSWORD: ${POSTGRES_APP_PASSWORD}
    volumes: 
      - $PWD/data_files/data:/var/lib/postgresql/data
      - $PWD/data_files/db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
    ports:
      - 8080:8080
      # - 9443:8443
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

  # salt-master:
  #   image: saltstack/salt:3003
  #   container_name: salt-master
  #   ports:
  #     - "4505:4505"
  #     - "4506:4506"
  #     - "8000:8000"
  #   environment: 
  #     SALT_MASTER_CONFIG: '{"auto_accept": true, "log_level": "info"}'
  #     SALT_SHARED_SECRET: 'testing123'
  #     # SALT_API_CONFIG: '{"rest_cherrypy": {"port": 8000, "ssl_crt": "/etc/pki/tls/certs/localhost.crt", "ssl_key": "/etc/pki/tls/certs/localhost.key"}, "external_auth": {"sharedsecret": {"salt": [".*", "@wheel", "@jobs", "@runner"]}}, "sharedsecret": "testing123", "log_level": "debug"}'
  #   volumes:
  #     - $PWD/srv:/srv

  # # this is to simulate an unresponsive minion
  # down-minion:
  #   image: saltstack/salt:3003
  #   container_name: down-minion
  #   environment:
  #     SALT_MINION_CONFIG: '{"master": "salt-master"}'
  #   hostname: down-minion
  #   depends_on:
  #     - salt-master

  # # this simulates a minion which returns an error
  # # specificly a pillar render error
  # bad-minion:
  #   image: saltstack/salt:3002
  #   container_name: bad-minion
  #   environment:
  #     SALT_MINION_CONFIG: '{"master": "salt-master"}'
  #   hostname: bad-minion
  #   depends_on:
  #     - salt-master

  # alpine3.12-minion:
  #   image: alpine-saltstack:3.12
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/Dockerfile-alpine3.12
  #   container_name: alpine3.12-minion
  #   hostname: alpine3.12-minion
  #   depends_on:
  #     - salt-master

  # ubuntu2004-minion:
  #   image: ubuntu-saltstack:20.04
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/Dockerfile-ubuntu2004
  #   container_name: ubuntu2004-minion
  #   hostname: ubuntu2004-minion
  #   depends_on:
  #     - salt-master

  # centos7-minion:
  #   image: centos-saltstack:7
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/Dockerfile-centos7
  #   container_name: centos7-minion
  #   hostname: centos7-minion
  #   depends_on:
  #     - salt-master

  # centos8-minion:
  #   image: centos-saltstack:8
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/Dockerfile-centos8
  #   container_name: centos8-minion
  #   hostname: centos8-minion
  #   depends_on:
  #     - salt-master

  # opensuseleap15.3-minion:
  #   image: opensuseleap-saltstack:15.3
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/Dockerfile-opensuseleap15.3
  #   container_name: opensuseleap15.3-minion
  #   hostname: opensuseleap15.3-minion
  #   depends_on:
  #     - salt-master