# Generated by Django 3.1.4 on 2020-12-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_system_info',
            name='highstate_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host_system_info',
            name='missing_hs_states',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='host_system_info',
            name='system_info',
            field=models.JSONField(default=dict),
        ),
    ]
