# Generated by Django 3.1.2 on 2020-10-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host_Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total', models.IntegerField()),
                ('packages', models.JSONField()),
                ('updates', models.IntegerField()),
                ('last_update', models.DateTimeField(verbose_name='date updated')),
            ],
            options={
                'db_table': 'host_packages',
            },
        ),
        migrations.CreateModel(
            name='Package_Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total', models.IntegerField()),
                ('hosts', models.JSONField()),
                ('updates', models.IntegerField()),
                ('last_update', models.DateTimeField(verbose_name='date updated')),
            ],
            options={
                'db_table': 'package_hosts',
            },
        ),
    ]
