FROM centos:7

# This uses the lastest 3000 of release since Centos 7 and python 3 is limited

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8

RUN yum install -y https://repo.saltstack.com/yum/redhat/salt-repo-3000.el7.noarch.rpm

RUN yum install -y salt-minion \
    && mkdir -p /etc/salt/minion.d \
    && echo '{"id": "test.minion.centos7", "master": "salt-master"}' > /etc/salt/minion.d/minion.conf

ENTRYPOINT ["/usr/bin/salt-minion"]
