FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8

RUN apt-get update \
    && apt-get install -y wget gnupg

RUN wget -O /tmp/key https://repo.saltstack.com/py3/ubuntu/$(grep VERSION_ID /etc/os-release | cut -d '=' -f 2 | tr -d '"')/amd64/latest/SALTSTACK-GPG-KEY.pub \
    && apt-key add /tmp/key \
    && echo "deb http://repo.saltstack.com/py3/ubuntu/$(grep VERSION_ID /etc/os-release | cut -d '=' -f 2 | tr -d '"')/amd64/latest $(grep VERSION_CODENAME /etc/os-release | cut -d "=" -f 2 | tr -d '"') main" \
        > /etc/apt/sources.list.d/saltstack.list \
    && apt-get update

RUN apt-get install -y salt-minion \
    && mkdir -p /etc/salt/minion.d \
    && echo '{"master": "salt-master"}' > /etc/salt/minion.d/minion.conf

ENTRYPOINT ["/usr/bin/salt-minion"]
