FROM centos:7

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8

RUN rpm --import https://repo.saltproject.io/py3/redhat/$(grep VERSION_ID /etc/os-release | cut -d "=" -f 2 | tr -d '"')/x86_64/latest/SALTSTACK-GPG-KEY.pub \
    && curl -fsSL https://repo.saltproject.io/py3/redhat/$(grep VERSION_ID /etc/os-release | cut -d "=" -f 2 | tr -d '"')/x86_64/latest.repo | tee /etc/yum.repos.d/salt.repo

RUN yum install -y salt-minion

RUN mkdir -p /etc/salt/minion.d \
    && echo '{"master": "salt-master"}' > /etc/salt/minion.d/minion.conf

ENTRYPOINT ["/usr/bin/salt-minion"]
