FROM centos:8

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8

RUN yum install -y https://repo.saltstack.com/py3/redhat/salt-py3-repo-3000.el8.noarch.rpm

RUN yum install -y salt-minion \
    && mkdir -p /etc/salt/minion.d \
    && echo '{"id": "test.minion.centos8", "master": "salt-master"}' > /etc/salt/minion.d/minion.conf

ENTRYPOINT ["/usr/bin/salt-minion"]
