version: '3.7'

services:
  salt-master:
    image: saltstack/salt:3000
    container_name: salt-master
    ports:
      - "4505:4505"
      - "4506:4506"
      - "8000:8000"
    environment: 
      SALT_MASTER_CONFIG: '{"auto_accept": true, "log_level": " debug"}'
      SALT_SHARED_SECRET: 'testing123'
    volumes:
      - $PWD/../salt_modules:/srv/salt/_modules
      - $PWD/pillar:/srv/pillar
      - $PWD/states:/srv/salt
      - $PWD/../:/opt/saltui

  salt-minion:
    image: saltstack/salt:3000
    container_name: salt-minion
    environment: 
      SALT_MINION_CONFIG: '{"id": "test.minion", "master": "salt-master"}'
    links:
      - salt-master:salt-master
