name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release 
    steps:
        uses: actions/checkout@v3

      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io/jsandas -u ${{ github.actor }} --password-stdin

      - name: Build and Push Images
        run: |
          docker build --tag ghcr.io/jsandas/saltui --tag ghcr.io/jsandas/saltui:${{  github.ref_name }} . 
          docker push --all-tags ghcr.io/jsandas/saltui