name: build support images

on:
  workflow_dispatch: {}
  schedule:
    - cron: "13 4 * * 0"

jobs:
  build_support_images:
    runs-on: ubuntu-latest
    name: Build Support Images
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push alpine3.16-minion
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/Dockerfile-alpine3.16
          tags: ghcr.io/jsandas/alpine-saltstack:3.16
          # platforms: linux/amd64,linux/arm64
          push: true

      - name: Build and push centos7-minion
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/Dockerfile-centos7
          tags: ghcr.io/jsandas/centos-saltstack:7
          # platforms: linux/amd64,linux/arm64
          push: true

      - name: Build and push opensuseleap15.4-minion
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/Dockerfile-opensuseleap15.4 
          tags: ghcr.io/jsandas/opensuseleap-saltstack:15.4
          # platforms: linux/amd64,linux/arm64
          push: true

      - name: Build and push ubuntu2004-minion
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/Dockerfile-ubuntu2004
          tags: ghcr.io/jsandas/ubuntu-saltstack:20.04
          # platforms: linux/amd64,linux/arm64
          push: true
